### ISSUE TITLE
リモートメールボックスを開くとB2が落ちる

### ISSUE THREAD

**Issue by Hiroki-H1974** [nonsava/BkCalendar#5]
最新の2.81.08でPOP3のリモートメールボックスを開き、メール一覧に
フォーカスするとB2.exeが落ちます。
イベントビューアで見ると、

障害が発生しているアプリケーション名: B2.exe、バージョン: 2.8.1.8、タイム スタンプ: 0x6726fe6f
障害が発生したモジュール名: BkCalendar.dll、 バージョン: 1.0.0.0、タイム スタンプ: 0x6732ee1c
例外コード: 0xc0000005
フォールト オフセット: 0x00026ba1
フォールト プロセス ID: 0x9F8
アプリケーションのフォールトの開始時刻: 0x1DB34C7DB6B35C4
Faulting アプリケーション パス:  C:\Program Files (x86)\RimArts\B2\B2.exe
Faulting モジュール パス:  C:\Program Files (x86)\RimArts\B2\PlugIns\BkCalendar.dll
Report Id: 56f9e1c7-21e6-417c-916a-f0569d915db2
Faulting パッケージの完全名: 
Faulting パッケージ相対アプリケーション ID: 

となっています。
プラグインをOFFにすると出ないため、このプラグインが原因ということは確実です。

**Comment by nonsava** [comment]
報告ありがとうございます。
不具合が再現いたしましたので修正しました。(1.0.1)

＃ 10年も前のものなので存在すら忘れてました…
